### ISSUE TITLE
vscode新建ps终端，自己cd到目录，加了第一章的代码，这两个路径，是相同的吗

### ISSUE THREAD

**Issue by k4m7v2pz** [Well2333/NoneBot2_NoobGuide#5]
![图片](https://user-images.githubusercontent.com/97567575/159161173-f0cd648d-79d7-474d-95ac-08412ed1ee68.png)

**Comment by Well2333** [comment]
你这目录结构好奇怪啊，bot.py的目录是哪个，一般来说哪个就是正确的workdir

**Comment by k4m7v2pz** [comment]
> 你这目录结构好奇怪啊，bot.py的目录是哪个，一般来说哪个就是正确的workdir

![图片](https://user-images.githubusercontent.com/97567575/159191132-293d9419-2ad4-45b4-8008-37b59aa6a6d5.png)

**Comment by k4m7v2pz** [comment]
程序可以运行，可以nb run，那应该就是对的，然后我又加上了自动cd到所在目录那个代码，很保险

**Comment by k4m7v2pz** [comment]
四章都看完了，机器人可以说话了，高兴的不得了

**Comment by Well2333** [comment]
能跑就行.jpg
